config/routes.rb
GeneroCity::Application.routes.draw do
  resources :favors

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root 'home#index'

end

app/models/favor.rb
class Favor < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessor :username

  def self.from_omniauth(auth)
    where(auth.slice(:provider,:uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.save
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_favor, only: [:show, :edit, :update, :destroy]

  # GET /favors
  # GET /favors.json
  def index
    @favors = Favor.all
  end

  # GET /favors/1
  # GET /favors/1.json
  def show
  end

  # GET /favors/new
  def new
    @favor = Favor.new
  end

  # GET /favors/1/edit
  def edit
  end

  # POST /favors
  # POST /favors.json
  def create
    @favor = Favor.new(favor_params)

    respond_to do |format|
      if @favor.save
        format.html { redirect_to @favor, notice: 'Favor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @favor }
      else
        format.html { render action: 'new' }
        format.json { render json: @favor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favors/1
  # PATCH/PUT /favors/1.json
  def update
    respond_to do |format|
      if @favor.update(favor_params)
        format.html { redirect_to @favor, notice: 'Favor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @favor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favors/1
  # DELETE /favors/1.json
  def destroy
    @favor.destroy
    respond_to do |format|
      format.html { redirect_to favors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favor
      @favor = Favor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favor_params
      params.require(:favor).permit(:address, :latitude, :longitude, :title, :description, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  alias_method :facebook, :all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/favors/_form.html.erb
<%= form_for(@favor) do |f| %>
  <% if @favor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favor.errors.count, "error") %> prohibited this favor from being saved:</h2>

      <ul>
      <% @favor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favors/edit.html.erb
<h1>Editing favor</h1>

<%= render 'form' %>

<%= link_to 'Show', @favor %> |
<%= link_to 'Back', favors_path %>

app/views/favors/index.html.erb
<h1>Listing favors</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @favors.each do |favor| %>
      <tr>
        <td><%= favor.address %></td>
        <td><%= favor.latitude %></td>
        <td><%= favor.longitude %></td>
        <td><%= favor.title %></td>
        <td><%= favor.description %></td>
        <td><%= favor.user %></td>
        <td><%= link_to 'Show', favor %></td>
        <td><%= link_to 'Edit', edit_favor_path(favor) %></td>
        <td><%= link_to 'Destroy', favor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favor', new_favor_path %>

app/views/favors/new.html.erb
<h1>New favor</h1>

<%= render 'form' %>

<%= link_to 'Back', favors_path %>

app/views/favors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @favor.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @favor.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @favor.longitude %>
</p>

<p>
  <strong>Title:</strong>
  <%= @favor.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @favor.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @favor.user %>
</p>

<%= link_to 'Edit', edit_favor_path(@favor) %> |
<%= link_to 'Back', favors_path %>

app/views/home/index.html.erb
<h1>Welcome to Genero-City</h1>
<% if current_user %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

<% else %>

<h3> Please sign up or sign in </h3>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeneroCity</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="user-nav">
      <% if current_user %>
        Logged in
        <%= link_to "Edit Profile", edit_user_registration_path %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>